version: '3'

services:
  frontend:
    image: stack-nextjs-image
    container_name: host-stack-frontend
    build:
      context: ./frontend
      dockerfile: ../provision/frontend/development/Dockerfile
    ports:
      - ${NEXT_PUBLIC_APP_PORT}:3000
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - main
    volumes:
      - ./frontend:/home/app

  backend:
    image: stack-nestjs-image
    container_name: host-stack-backend
    build:
      context: ./backend
      dockerfile: ../provision/backend/development/Dockerfile
    ports:
      - ${NEST_PORT}:${NEST_PORT}
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - main
    volumes:
      - ./backend:/var/www/stack

  database:
    image: postgres:15.3
    container_name: host-stack-database
    restart: always
    env_file:
    - .env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - main

networks:
  main:
    driver: bridge
